---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-pipelines
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-pipelines-memcached
  namespace: memcached-operator
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-pipelines
  namespace: cicd
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - triggers.tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: test-pipelines
rules:
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - use
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
# Required for getting write priveleges
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - pipelines-scc
  verbs:
  - use
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - clusterurlmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - clusterurlmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.openshift.io
  resources:
  - routemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - routemonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-pipelines
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-pipelines
  namespace: cicd
subjects:
- kind: ServiceAccount
  name: test-pipelines
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-pipelines-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-pipelines
subjects:
- kind: ServiceAccount
  name: test-pipelines
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-pipelines-clusterinterceptors
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-pipelines-clusterinterceptors
subjects:
- kind: ServiceAccount
  name: test-pipelines
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-pipelines-memcached-ns
  namespace: memcached-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-pipelines-memcached
  namespace: memcached-operator
subjects:
- kind: ServiceAccount
  name: test-pipelines
  namespace: cicd