apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-memcached-operator-version
  namespace: cicd
spec:
  steps:
    - args:
        - |-
          version=$(oc describe sub memcached-operator-subscription -n memcached-operator | grep "Current CSV:" | tr "-" "\n" | tail -1)
          if [ -z "$version" ]
          then
            echo "Couldn't determine installation version"
            exit -1
          else
            echo "Found with commit hash:"
            echo ${version}
            echo ${version} > installed_commit
          fi
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      resources: {}
      workingDir: /workspace/output
  workspaces:
    - name: output
