apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: memcached-operator-subscription
  namespace: memcached-operator
spec:
  channel: alpha
  name: memcached-operator
  source: memcached-operator-registry
  sourceNamespace: memcached-operator
